# Generated by Django 3.2.2 on 2021-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_advanced', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
