# Generated by Django 3.2.2 on 2021-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='passport',
            field=models.FileField(default=' ', upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
