# Generated by Django 3.2.2 on 2021-06-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210613_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='public/pets'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='passport',
            field=models.FileField(upload_to='private/documents'),
        ),
    ]
