# Generated by Django 3.2.2 on 2021-05-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
