# Generated by Django 3.2.3 on 2021-07-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0004_python_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='created_by',
        ),
    ]
