# Generated by Django 3.2.3 on 2021-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210616_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_url',
            field=models.FileField(upload_to='pets_images'),
        ),
    ]
